### ISSUE TITLE
Table is not rendering correctly and is loosing some cells

### ISSUE THREAD

**Issue by numToStr** [zhiburt/tabled#110] opened 2022-04-13 09:27 UTC
Thank you for making this wonderful crate ❤️ 

I've been using `tabled` in my tool to render some data in tabular form but I am facing some issues regarding the rendering of the table. The data that I am trying to render is the following

```
CMode                                                                   *CMode*
    Comment modes - Can be manual or computed in operator-pending phase

    Fields: ~
        {number}  (toggle)     Toggle action
        {number}  (comment)    Comment action
        {number}  (uncomment)  Uncomment action
```

There is only one limitation that is the data has 80 character limit on a single line everything else should be wrapped. So I came up with the following

<details>
<summary>Code</summary>

```rust
let fields = Table::new([
    ["{number}", "(toggle)", "Toggle action"],
    ["{number}", "(comment)", "Comment action"],
    ["{number}", "(uncomment)", "Uncomment action"],
])
.with(Disable::Row(..1))
.with(Header("Fields: ~"))
// .with(Style::blank())
.with(Margin::new(3, 0, 0, 0))
.with(Modify::new(Columns::new(..1)).with(Padding::new(4, 0, 0, 0)))
.with(Modify::new(Cell(0, 0)).with(Padding::new(0, 0, 0, 0)))
.with(Modify::new(Full).with(Alignment::left()));

let head = Table::new([
    ["Cmode", "*CMode*"],
    [
        "Comment modes - Can be manual or computed in operator-pending phase",
        "",
    ],
    ["", ""],
    [fields.to_string().as_str(), ""],
])
.with(Disable::Row(..1))
.with(MaxWidth::wrapping(83))
.with(MinWidth::new(83))
// .with(Style::blank())
.with(Modify::new(Cell(1, 0)).with(Padding::new(4, 0, 0, 0)))
.with(Modify::new(Columns::new(1..=2)).with(Alignment::right()))
.with(Modify::new(Columns::new(..1)).with(Alignment::left()))
.with(Modify::new(Cell(1, 0)).with(Span::column(2)));
```

</details>

<details>
<summary>Output</summary>

```
+---------------------------------------------------------+--------------+
| Cmode                                                   |     *CMode*  |
+---------------------------------------------------------+--------------+
|    Comment modes - Can be manual or computed in operator-pending phase |
+---------------------------------------------------------+--------------+
|                                                         |              |
+---------------------------------------------------------+--------------+
|     Fields: ~                                           |              |
|    +------------+-------------+------------------+      |              |
|    |    {number}| (toggle)    | Toggle action    |      |              |
|    +------------+-------------+------------------+      |              |
|    |    {number}| (comment)   | Comment action   |      |              |
|    +------------+-------------+------------------+      |              |
|    |    {number}| (uncomment) | Uncomment action |      |              |
|    +------------+-------------+------------------+      |              |
+---------------------------------------------------------+--------------+
```

</details>

As you can see, the table doesn't respect (underflow) the width which I believe is because of `Span` because when I remove the last line i.e `.with(Modify::new(Cell(1, 0)).with(Span::column(2)))` from the above code then the width goes above the specified `MaxWidth`.

<details>
<summary>Details</summary>

```
+------------------------------------------------------------------------+----------+
| Cmode                                                                  | *CMode*  |
+------------------------------------------------------------------------+----------+
|    Comment modes - Can be manual or computed in operator-pending phase |          |
+------------------------------------------------------------------------+----------+
|                                                                        |          |
+------------------------------------------------------------------------+----------+
|     Fields: ~                                                          |          |
|    +------------+-------------+------------------+                     |          |
|    |    {number}| (toggle)    | Toggle action    |                     |          |
|    +------------+-------------+------------------+                     |          |
|    |    {number}| (comment)   | Comment action   |                     |          |
|    +------------+-------------+------------------+                     |          |
|    |    {number}| (uncomment) | Uncomment action |                     |          |
|    +------------+-------------+------------------+                     |          |
+------------------------------------------------------------------------+----------+
```

</details>

### Data loss

Now, If I extend the text in the second row then the cell at `0,1` loses its content.

<details>
<summary>Code</summary>

```rust
let fields = Table::new([
    ["{number}", "(toggle)", "Toggle action"],
    ["{number}", "(comment)", "Comment action"],
    ["{number}", "(uncomment)", "Uncomment action"],
])
.with(Disable::Row(..1))
.with(Header("Fields: ~"))
// .with(Style::blank())
.with(Margin::new(3, 0, 0, 0))
.with(Modify::new(Columns::new(..1)).with(Padding::new(4, 0, 0, 0)))
.with(Modify::new(Cell(0, 0)).with(Padding::new(0, 0, 0, 0)))
.with(Modify::new(Full).with(Alignment::left()));

let head = Table::new([
    ["Cmode", "*CMode*"],
    [
        "Comment modes - Can be manual or computed in operator-pending phase. I am going to extend this line and see what happens to the table.",
        "",
    ],
    ["", ""],
    [fields.to_string().as_str(), ""],
])
.with(Disable::Row(..1))
.with(MinWidth::new(83))
.with(MaxWidth::wrapping(83))
// .with(Style::blank())
.with(Modify::new(Cell(1, 0)).with(Padding::new(4, 0, 0, 0)))
.with(Modify::new(Columns::new(1..=2)).with(Alignment::right()))
.with(Modify::new(Columns::new(..1)).with(Alignment::left()))
.with(Modify::new(Cell(1, 0)).with(Span::column(2)));
```

</details>

<details>
<summary>Details</summary>

```
+-----------------------------------------------------------------+--------------+
| Cmode                                                           |              |
+-----------------------------------------------------------------+--------------+
|    Comment modes - Can be manual or computed in operator-pending phase. I am go|
|    ing to extend this line and see what happens to the table.                  |
+-----------------------------------------------------------------+--------------+
|                                                                 |              |
+-----------------------------------------------------------------+--------------+
|     Fields: ~                                                   |              |
|    +------------+-------------+------------------+              |              |
|    |    {number}| (toggle)    | Toggle action    |              |              |
|    +------------+-------------+------------------+              |              |
|    |    {number}| (comment)   | Comment action   |              |              |
|    +------------+-------------+------------------+              |              |
|    |    {number}| (uncomment) | Uncomment action |              |              |
|    +------------+-------------+------------------+              |              |
+-----------------------------------------------------------------+--------------+
```

</details>

I might be doing something wrong here so if you can help me with this that will be very helpful.

**Comment by zhiburt** [comment] 2022-04-13 10:09
Hi @numToStr 

You've used almost every available tool we have :smile: 

Apparently something is going on when you do `Disable` I'll investigate later today.

But please let me know if the following resolves your issue and the result is as expected.

```rust
    let data = [
        ["{number}", "(toggle)", "Toggle action"],
        ["{number}", "(comment)", "Comment action"],
        ["{number}", "(uncomment)", "Uncomment action"],
    ];

    let fields = Builder::from_iter(data)
        .build()
        .with(Header("Fields: ~"))
        .with(Margin::new(3, 0, 0, 0))
        .with(Modify::new(Columns::new(..1)).with(Padding::new(4, 0, 0, 0)))
        .with(Modify::new(Cell(0, 0)).with(Padding::new(0, 0, 0, 0)))
        .with(Modify::new(Full).with(Alignment::left()))
        .to_string();

    let data = [
            ["Cmode", "*CMode*"],
            [
                "Comment modes - Can be manual or computed in operator-pending phase. I am going to extend this line and see what happens to the table.",
                "",
            ],
            ["", ""],
            [&fields, ""],
        ];

    let head = Builder::from_iter(data).build()
        .with(Modify::new(Cell(1, 0)).with(Padding::new(4, 0, 0, 0)))
        .with(Modify::new(Columns::new(1..=2)).with(Alignment::right()))
        .with(Modify::new(Columns::new(..1)).with(Alignment::left()))
        .with(Modify::new(Cell(1, 0)).with(Span::column(2)))
        .with(MinWidth::new(83))
        .with(MaxWidth::wrapping(83));

    println!("{}", head)
```

```
+--------------------------------------------------------------+------------------+
| Cmode                                                        |          *CMode* |
+--------------------------------------------------------------+------------------+
|    Comment modes - Can be manual or computed in operator-pending phase. I am goi|
|    ng to extend this line and see what happens to the table.                    |
+--------------------------------------------------------------+------------------+
|                                                              |                  |
+--------------------------------------------------------------+------------------+
|     Fields: ~                                                |                  |
|    +------------+-------------+------------------+           |                  |
|    |    {number}| (toggle)    | Toggle action    |           |                  |
|    +------------+-------------+------------------+           |                  |
|    |    {number}| (comment)   | Comment action   |           |                  |
|    +------------+-------------+------------------+           |                  |
|    |    {number}| (uncomment) | Uncomment action |           |                  |
|    +------------+-------------+------------------+           |                  |
+--------------------------------------------------------------+------------------+
```

Basically I've used `tabled::Builder` which suppose to be used on a dynamic data set.

**Comment by zhiburt** [comment] 2022-04-13 10:13
Ohaaaa I found the issue seems to be.

You just used `MinWidth` and `MaxWidth` before you applied a `Span`.
It matters quite a bit.

Try to use it at the end.

**Comment by numToStr** [comment] 2022-04-13 11:34
@zhiburt Thank you so much. `Builder` seems to prevent the content loss but somehow the table is not respecting the width in case of spanning. Now I am spanning all the rows except the first one. You can clearly see that width is still messed up

![image](https://user-images.githubusercontent.com/24727447/163171153-caf1cbc7-7b48-4429-ad31-5821d0db3e10.png)

**Comment by zhiburt** [comment] 2022-04-13 11:44
I see, but it must be the same in both tables?

Could you provide an example?

**Comment by numToStr** [comment] 2022-04-13 12:05
Yes, as you can see in the screenshot both table's width are incorrect to what i specified which is `MinWidth::new(80)`.

**Comment by numToStr** [comment] 2022-04-13 12:26
@zhiburt Here is an example that gives the same output like the screenshot

```rust
#[macro_export]
macro_rules! section {
    ($name: expr, $tag: expr, $desc: expr, $($data: expr),* $(,)?) => {
        tabled::builder::Builder::from_iter([
            [$name, format!("*{}*", $tag).as_str()],
            [$desc, "".into()],
            ["".into(), "".into()],
            $(
                [$data, "".into()],
            )*
        ]).build()
        // .with(tabled::Style::blank())
        .with(tabled::Modify::new(tabled::Full).with(tabled::Padding::new(0, 0, 0, 0)))
        .with(tabled::Modify::new(tabled::Cell(1, 0)).with(tabled::Padding::new(4, 0, 0, 0)))
        .with(tabled::Modify::new(tabled::Columns::new(1..=2)).with(tabled::Alignment::right()))
        .with(tabled::Modify::new(tabled::Columns::new(..1)).with(tabled::Alignment::left()))
        .with(tabled::Modify::new(tabled::Rows::new(1..)).with(tabled::Span::column(2)))
        .with(tabled::MinWidth::new(80))
        .with(tabled::MaxWidth::wrapping(80))
    };
}

#[macro_export]
macro_rules! child_table {
    ($title: expr, $data: expr) => {
        tabled::builder::Builder::from_iter($data)
            .build()
            .with(tabled::Style::blank())
            .with(tabled::Header($title))
            .with(tabled::Margin::new(4, 0, 0, 0))
            .with(
                tabled::Modify::new(tabled::Columns::new(..1))
                    .with(tabled::Padding::new(4, 0, 0, 0)),
            )
            .with(tabled::Modify::new(tabled::Cell(0, 0)).with(tabled::Padding::new(0, 0, 0, 0)))
            .with(tabled::Modify::new(tabled::Full).with(tabled::Alignment::left()))
            .with(
                tabled::Modify::new(tabled::Columns::new(2..)).with(tabled::MaxWidth::wrapping(45)),
            )
    };
}

fn main() {
    // to give you the idea of the width
    println!("{}", "=".repeat(80));

    let fields = child_table!(
        "Fields: ~",
        [
            ["{toggle}", "(number)", "Toggle action"],
            ["{comment}", "(number)", "Comment action"],
            ["{uncomment}", "(number)", "Uncomment action"]
        ]
    );

    let class = section!(
        "Cmode",
        "*CMode*",
        "Comment modes - Can be manual or computed in operator-pending phase",
        fields.to_string().as_str()
    );

    println!("{}", class);

    let params = child_table!("Parameters: ~", [["{string}", "(str)", "String to check"],]);

    let returns = child_table!(
        "Returns: ~",
        [
            ["{string}", "Indent chars"],
            ["{string}", "Length of the indent chars"],
        ]
    );

    let func = section!(
        "U.grab_ident({str})",
        "*U.grab_ident*",
        "Takes out the leading indent from the line",
        params.to_string().as_str(),
        returns.to_string().as_str()
    );

    println!("{}", func)
}
```

**Comment by zhiburt** [comment] 2022-04-13 12:35
@numToStr must be fixed tend to believe.

It was a bug.

Could you switch to `tabled = { git = "https://github.com/zhiburt/tabled/", branch = "master" }` and verify it?

PS: Seems like you have a healthy eyes if you managed to see the difference in width :smile:
       I hope it will stay the same if this is the case.

**Comment by numToStr** [comment] 2022-04-13 12:39
> Could you switch to `tabled = { git = "https://github.com/zhiburt/tabled/", branch = "master" }` and verify it?

Doing it right now :)

> PS: Seems like you have a healthy eyes if you managed to see the difference in width smile I hope they will stay the same if this is the case.

Hahaha, thanks! I also wish you well :)

**Comment by zhiburt** [comment] 2022-04-13 12:43
Great,
I'll try to bump `tabled` to `0.6.1` with the fix a bit later today.

Thank you for addressing the issue once again.
And take care.

If you consider that the issue is closed you can close this issue.
Or you can wait until a `0.6.1`.

**Comment by numToStr** [comment] 2022-04-13 12:44
@zhiburt You are amazing. Now width is perfect, wrapping works, everything works like a charm. Thanks! you made my day.

Sure, I'll go ahead and close the issue.

**Closed** 2022-04-13 12:44 UTC
